### ISSUE TITLE
Number formatting with comma instead of decimal point leads to corrupted JSON files

### ISSUE THREAD

**Issue by AndisGrossteins** [JustinBrownDev/Bibitinator#1]
Hi,
I'm the same person who asked if you'd like to collab on Reddit.

I finally got to test Bibinator and right away discovered an issue; The save code seems to be using a locale-dependent decimal number formatting which breaks JSON. Many languages (culture in .Net/MS parlance), mine included, use a comma instead of a decimal point.

To avoid this issue you should specify [CultureInfo.InvariantCulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-6.0) when outputting and displaying numeric values or use a [NumberFormatInfo](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberformatinfo?view=net-6.0) object and set its properties.

I'll try to fix this issue and submit a PR.

BTW, which Visual Studio version are you using for this project?
I have VS 2019 & 2017 but haven't launched any of them for a long time, so it's gonna take a while to install updates.

**Comment by JustinBrownDev** [comment]
Thanks for the feedback! I’ll make this fix right now. I added a check for
leading decimal points but I’ll definitely implement a more sophisticated
formatting version.
Also, I’m using VS 2022

**Comment by AndisGrossteins** [comment]
Already tried and failed to open the solution in VS 2019. I'm looking through the code while VS 2022 is installing in the background.

Not sure if you've already noticed that "Save as copy" deletes the original file but I'll submit a new issue since it is a different issue.

**Comment by JustinBrownDev** [comment]
Make sure your looking through the newest version, it doesn’t delete the
original copy for me?

**Comment by AndisGrossteins** [comment]
Great, I've closed issue #2 as it seems you've fixed that at some point.

It looks like this issue affects only the genes object and now I see why. The number formatting should not be an issue after rewriting `BibiteEditor.ReplaceValuesInBibiteSettings` method to set values programmatically instead of using string functions.

Looks like you've already created model objects for JSON serialization. The `BibiteReflect` subclasses could be used to also validate the inputs and convert to appropriate data types in class property setters.

**Comment by JustinBrownDev** [comment]
I've added a check for commas in the functions where this was causing an issue, I've removed the models in favor of dynamic deserialization of the json files. I have not gotten confirmation whether this fixed the issue and I'm not sure exactly how to test it myself.

**Comment by JustinBrownDev** [comment]
closing this issue, if it persists i'm available via reddit & discord, or open a new issue
