### ISSUE TITLE
Bibite editor: clicking "Reset" in the genes editor adds all synapses to the brain editor again

### ISSUE THREAD

**Issue by quaris628** [JustinBrownDev/Bibitinator#9]
Steps to reproduce:
1. Load a bibite with at least 1 synapse
2. Open the genes editor
3. Click "Reset"
4. Open the brain editor
5. See that all they synapses are duplicated (and then cry)
You can do this multiple times for a bibite and get multiple sets of duplicate synapses

Explanation (as I understand it):
It looks like the build genes editor function also changes the brain editor UI, including by adding all the synapses. This function is called in two places: when loading the whole bibites editor, and when clicking the gene reset button. It makes sense to update the brain editor UI at the same time as updating the genes UI in the first case. But in the second case, it causes the synapse list to get another set of duplicates appended each time it runs (since the list of synapses isn't cleared in between).

Suggested fix:
Move the code currently inside the build genes editor function to a separate build brain UI function. Call both of these functions when loading the whole bibite editor, but call only the genes editor one when resetting genes.
(Another fix option is to clear the list of synapses before adding them, but that still leaves the function design kinda messy.)

**Comment by JustinBrownDev** [comment]
`
private void BrainResetButton_Click(object sender, EventArgs e)
        {
            bibCol.dynRoot["brain"] = dynRootOriginal["brain"].DeepClone();
            BrainTrace();
            BrainEditorPanel.Controls.Clear();
            List<JToken> synaps = bibCol.dynRoot["brain"]["Synapses"].ToList();
            foreach (JToken synap in synaps)
            {
                AddSynapsePanel(synap);
            }

}
`
fixed this by saving a deepclone of the json object when the bibite is loaded for the first time and resetting it to that,

**Comment by quaris628** [comment]
Sweet!
